# 本文件用来配置项目的通用连接信息，比如数据库、消息中间件、缓存、文件存储服务器等相关信息的配置

########################################################
### Mysql conf   mysql数据库的连接信息
########################################################
public:
  spring:
    datasource:
      host: 127.0.0.1
      port: 3306
      username: root
      password: toor

########################################################
### Redis 集群
########################################################

########################################################
### kafka集群配置文件
########################################################

########################################################
### consul的相关信息
########################################################

########################################################
###  fdfs 相关信息
########################################################